import { StyleSheet } from "react-native";

const COLORS = {
  background: '#FFF8E7',
  foreground: '#3E2723',
  card: '#ffffff',
  cardForeground: '#3E2723',
  primary: '#8B4513',
  primaryForeground: '#ffffff',
  secondary: '#F5E6D3',
  secondaryForeground: '#3E2723',
  muted: '#F5E6D3',
  mutedForeground: '#8D6E63',
  accent: '#D4A574',
  accentForeground: '#3E2723',
  destructive: '#d4183d',
  destructiveForeground: '#ffffff',
  border: 'rgba(139, 69, 19, 0.15)',
  inputBackground: '#ffffff',
  switchBackground: '#D4A574',
};

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: COLORS.card,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.secondary,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: COLORS.foreground,
  },
  headerSpacer: {
    width: 40,
  },
  scrollView: {
    flex: 1,
  },
  card: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    padding: 20,
    marginHorizontal: 16,
    marginTop: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  profileHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 24,
  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: {
    fontSize: 32,
    fontWeight: "600",
    color: COLORS.primaryForeground,
  },
  profileInfo: {
    marginLeft: 16,
    flex: 1,
  },
  profileName: {
    fontSize: 18,
    fontWeight: "500",
    color: COLORS.foreground,
  },
  infoSection: {
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    paddingTop: 16,
  },
  infoItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  editingItem: {
    paddingBottom: 16,
  },
  noBorder: {
    borderBottomWidth: 0,
  },
  infoIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.secondary,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
  },
  infoTextContainer: {
    marginLeft: 12,
    flex: 1,
  },
  infoHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  infoLabel: {
    fontSize: 12,
    color: COLORS.mutedForeground,
  },
  editText: {
    fontSize: 14,
    color: COLORS.accent,
    fontWeight: "500",
  },
  infoValue: {
    fontSize: 16,
    color: COLORS.foreground,
    fontWeight: "500",
  },
  editInput: {
    fontSize: 16,
    color: COLORS.foreground,
    fontWeight: "500",
    backgroundColor: COLORS.inputBackground,
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginTop: 4,
  },
  editActionsWrapper: {
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    paddingBottom: 12,
    marginBottom: 12,
  },
  editActions: {
    flexDirection: "row",
    gap: 12,
    paddingLeft: 52,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: COLORS.secondary,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  cancelButtonText: {
    color: COLORS.foreground,
    fontSize: 14,
    fontWeight: "500",
  },
  saveButton: {
    flex: 1,
    backgroundColor: COLORS.primary,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
  },
  saveButtonDisabled: {
    backgroundColor: COLORS.mutedForeground,
    opacity: 0.5,
  },
  saveButtonText: {
    color: COLORS.primaryForeground,
    fontSize: 14,
    fontWeight: "600",
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "500",
    color: COLORS.foreground,
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  preferenceItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  preferenceContent: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  iconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  purpleIcon: {
    backgroundColor: "#EDE9FE",
  },
  blueIcon: {
    backgroundColor: "#DBEAFE",
  },
  greenIcon: {
    backgroundColor: "#DCFCE7",
  },
  preferenceText: {
    marginLeft: 12,
    flex: 1,
  },
  preferenceTitle: {
    fontSize: 16,
    fontWeight: "500",
    color: COLORS.foreground,
    marginBottom: 2,
  },
  preferenceSubtext: {
    fontSize: 14,
    color: COLORS.mutedForeground,
  },
  switch: {
    width: 48,
    height: 28,
    borderRadius: 14,
    backgroundColor: COLORS.muted,
    padding: 2,
    justifyContent: "center",
  },
  switchActive: {
    backgroundColor: COLORS.switchBackground,
  },
  switchThumb: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: COLORS.card,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  switchThumbActive: {
    alignSelf: "flex-end",
  },
  disconnectButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.card,
  },
  disconnectButtonText: {
    fontSize: 14,
    fontWeight: "500",
    color: COLORS.foreground,
  },
  actionsContainer: {
    marginHorizontal: 16,
    marginTop: 16,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingVertical: 16,
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  actionButtonText: {
    fontSize: 16,
    fontWeight: "500",
    color: COLORS.foreground,
    marginLeft: 12,
  },
  logoutButton: {
    borderColor: 'rgba(212, 24, 61, 0.3)',
    backgroundColor: 'rgba(212, 24, 61, 0.05)',
  },
  logoutText: {
    color: COLORS.destructive,
  },
  versionText: {
    textAlign: "center",
    fontSize: 14,
    color: COLORS.mutedForeground,
    marginTop: 24,
    marginBottom: 32,
  },
});