// styles/HistoryScreen.styles.ts
import { StyleSheet } from 'react-native';
import { ThemeColors } from '../../theme/colors';

export const getStyles = (theme: ThemeColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.background,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.background,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: theme.secondary,
    fontWeight: '600',
  },
  header: {
    backgroundColor: theme.surface,
    paddingTop: 60,
    paddingBottom: 16,
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.accent,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: theme.primary,
    flex: 1,
    textAlign: 'center',
  },
  headerRight: {
    width: 80,
  },
  sessionCount: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.secondary,
    textAlign: 'right',
  },
  listContent: {
    padding: 24,
    paddingBottom: 40,
  },
  historyCard: {
    backgroundColor: theme.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 2,
    borderColor: theme.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    position: 'relative',
  },
  favoriteButtonPosition: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    zIndex: 1,
    width: 32,
    height: 32,
  },
  historyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  dateTimeContainer: {
    flex: 1,
  },
  dateText: {
    fontSize: 16,
    fontWeight: '700',
    color: theme.primary,
  },
  timeText: {
    fontSize: 13,
    color: theme.secondary,
    marginTop: 2,
  },
  drinksCountBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.accent,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  drinksCountText: {
    fontSize: 12,
    fontWeight: '700',
    color: theme.secondary,
  },
  contextRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: theme.border,
    marginBottom: 12,
  },
  contextItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  contextEmoji: {
    fontSize: 18,
  },
  contextLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.textSecondary,
  },
  contextDivider: {
    width: 1,
    height: 20,
    backgroundColor: theme.border,
  },
  drinksPreview: {
    gap: 8,
  },
  previewTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: theme.secondary,
    marginBottom: 4,
  },
  drinkPreviewItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  rankDot: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: theme.secondary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  rankDotText: {
    fontSize: 10,
    fontWeight: '700',
    color: theme.surface,
  },
  drinkPreviewName: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.primary,
    flex: 1,
  },
  moreText: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.secondary,
    fontStyle: 'italic',
    marginTop: 4,
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  emptyText: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.textSecondary,
    marginTop: 16,
  },
  emptySubtext: {
    fontSize: 14,
    color: theme.muted,
    marginTop: 8,
    textAlign: 'center',
    paddingHorizontal: 40,
  },
});