// styles/RecommendationsScreen.styles.ts
import { StyleSheet } from 'react-native';
import { ThemeColors } from '../../theme/colors';

export const getStyles = (theme: ThemeColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.background,
  },
  header: {
    backgroundColor: theme.surface,
    paddingTop: 60,
    paddingBottom: 16,
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.accent,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerCenter: {
    flex: 1,
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: theme.primary,
  },
  headerSubtitle: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.secondary,
    marginTop: 2,
  },
  headerRight: {
    width: 40,
  },
  contextCard: {
    backgroundColor: theme.surface,
    marginHorizontal: 24,
    marginTop: 16,
    marginBottom: 8,
    padding: 16,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: theme.border,
  },
  contextHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  contextTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.primary,
  },
  contextDetails: {
    gap: 8,
  },
  contextItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  contextLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.secondary,
    width: 80,
  },
  contextValue: {
    fontSize: 13,
    fontWeight: '700',
    color: theme.primary,
    flex: 1,
  },
  listHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 16,
  },
  listHeaderText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.secondary,
  },
  listContent: {
    padding: 24,
    paddingTop: 0,
    paddingBottom: 40,
  },
  drinkCard: {
    backgroundColor: theme.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 2,
    borderColor: theme.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    position: 'relative',
  },
  rankBadge: {
    position: 'absolute',
    top: -8,
    left: 16,
    backgroundColor: theme.secondary,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    zIndex: 1,
  },
  rankBadgeFirst: {
    backgroundColor: '#F59E0B',
  },
  rankBadgeSecond: {
    backgroundColor: '#9CA3AF',
  },
  rankBadgeThird: {
    backgroundColor: '#D97706',
  },
  rankText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  favoriteButtonPosition: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    zIndex: 2,
  },
  scoreBadge: {
    position: 'absolute',
    top: -8,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
    zIndex: 1,
  },
  scoreText: {
    fontSize: 11,
    fontWeight: '700',
  },
  drinkHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
    marginTop: 8,
  },
  drinkTitleContainer: {
    flex: 1,
  },
  drinkName: {
    fontSize: 20,
    fontWeight: '700',
    color: theme.primary,
    marginBottom: 2,
  },
  drinkNameArabic: {
    fontSize: 14,
    color: theme.secondary,
    fontWeight: '500',
  },
  reasonsContainer: {
    backgroundColor: theme.success + '15',
    padding: 12,
    borderRadius: 12,
    marginBottom: 12,
  },
  reasonsTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: theme.success,
    marginBottom: 8,
  },
  reasonItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  reasonText: {
    fontSize: 13,
    color: theme.text,
    flex: 1,
  },
  flavorContainer: {
    marginBottom: 12,
  },
  flavorTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: theme.secondary,
    marginBottom: 6,
  },
  flavorTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  flavorTag: {
    backgroundColor: theme.accent + '30',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.border,
  },
  flavorText: {
    fontSize: 11,
    fontWeight: '600',
    color: theme.secondary,
  },
  drinkDetails: {
    gap: 12,
    marginBottom: 12,
  },
  detailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  detailIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  detailLabel: {
    fontSize: 11,
    color: theme.secondary,
    fontWeight: '500',
  },
  detailValue: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.primary,
  },
  dietaryBadges: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  dietaryBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  dietaryText: {
    fontSize: 11,
    fontWeight: '700',
  },
});